services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrong!Passw0rd
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - ai_mysql_data:/var/lib/mysql

volumes:
  ai_mysql_data: